language: cpp
dist: trusty

matrix:
  include:
    - os: linux
      compiler: gcc-5
      env: COMPILER=g++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5

    - os: linux
      compiler: clang-3.6
      env: COMPILER=clang++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty
          packages:
            - g++-5
            - clang-3.6
            - llvm-3.6-dev # for LLVMGold.so
            - binutils-gold

    - os: osx
      osx_image: xcode8.3
      compiler: clang

branches:
  only:
    - master

before_install:
  - export SYSTEM=$(uname)
  - if [ "$SYSTEM" != "Darwin" ]; then sudo apt-get update -qq; fi
  - if [ "$SYSTEM" != "Darwin" ]; then sudo apt-get install build-essential m4 libgmp3-dev cmake; fi

install:
  - if [ "$COMPILER" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$COMPILER" = "clang++" ]; then export CXX="clang++-3.6" CC="clang-3.6"; fi
  - if [ "$COMPILER" = "clang++" ]; then sudo update-alternatives --install /usr/bin/ld ld /usr/bin/ld.gold 20; fi
  - if [ "$COMPILER" = "clang++" ]; then sudo update-alternatives --install /usr/bin/ld ld /usr/bin/ld.bfd 10; fi
  - cd StormLib
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_DYNAMIC_MODULE=1 ..
  - make
  - sudo make install
  - cd ../..
  - cd bncsutil/src/bncsutil
  - make
  - sudo make install
  - cd ../../..

script:
  - make
  - sudo make install

notifications-policy: &notifications-policy
  on_success: change
  on_failure: always

notifications:
  email: false
  irc:
    channels:
      - "irc.quakenet.org#clan007"
    <<: *notifications-policy
